// Build script for the Bedrock Bridge behavior pack.
//
// Two steps run in order:
//   1. Generate `src/generated/module-versions.ts` from the Script API module
//      versions declared in `manifest.json` — the single source of truth the
//      capability probe reports at handshake (see src/capabilities/).
//   2. Bundle `src/index.ts` into the single `scripts/main.js` file BDS loads.
//      The `@minecraft/*` modules are provided by BDS at runtime, so they are
//      marked external and never bundled.

import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";

const SCRIPT_MODULES = ["@minecraft/server", "@minecraft/server-net", "@minecraft/server-admin"];

/** Reads the manifest's `dependencies` block into a name → version map. */
async function readManifestModuleVersions() {
  const manifest = JSON.parse(await readFile("manifest.json", "utf8"));
  const versions = {};
  for (const dependency of manifest.dependencies ?? []) {
    if (typeof dependency.module_name === "string") {
      versions[dependency.module_name] = dependency.version;
    }
  }
  for (const name of SCRIPT_MODULES) {
    if (!(name in versions)) {
      throw new Error(`manifest.json is missing a dependency entry for '${name}'`);
    }
  }
  return versions;
}

/** Reads the behavior pack's own version from the manifest header. */
async function readBehaviorPackVersion() {
  const manifest = JSON.parse(await readFile("manifest.json", "utf8"));
  const version = manifest.header?.version;
  if (!Array.isArray(version) || version.length !== 3) {
    throw new Error("manifest.json header.version must be a [major, minor, patch] array");
  }
  return version.join(".");
}

/** Emits the generated module-versions module the capability probe imports. */
async function generateModuleVersions() {
  const versions = await readManifestModuleVersions();
  const packVersion = await readBehaviorPackVersion();
  const entries = SCRIPT_MODULES.map(
    (name) => `  ${JSON.stringify(name)}: ${JSON.stringify(versions[name])},`,
  ).join("\n");
  const contents = `// GENERATED by build.mjs from manifest.json — do not edit by hand.
//
// The Script API module versions the behavior pack declares it depends on, and
// the behavior pack's own version. The capability probe reports these at
// handshake; the Script API exposes no runtime version accessor, so the
// manifest is the single source of truth.

/** Declared version of each Script API module, keyed by module name. */
export const MODULE_VERSIONS: Readonly<Record<string, string>> = {
${entries}
};

/** The behavior pack's version, from \`manifest.json\` header.version. */
export const BEHAVIOR_PACK_VERSION = ${JSON.stringify(packVersion)};
`;
  await mkdir("src/generated", { recursive: true });
  await writeFile("src/generated/module-versions.ts", contents);
}

await generateModuleVersions();

await build({
  entryPoints: ["src/index.ts"],
  outfile: "scripts/main.js",
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2020",
  external: SCRIPT_MODULES,
  legalComments: "none",
  banner: {
    js: [
      "// Bedrock Bridge behavior pack — generated bundle. Do not edit.",
      "// Edit the sources under src/ and rebuild with `npm run build`.",
      "// https://github.com/chapmanjw/minecraft-bedrock-mcp-behavior-pack",
    ].join("\n"),
  },
});

console.log("Bundled src/index.ts -> scripts/main.js");
